// <auto-generated />
using System;
using Annonce.Services.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annonce.Services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Annonce.Services.Models.Annonces", b =>
                {
                    b.Property<int>("AnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnonceId"), 1L, 1);

                    b.Property<string>("AnnonceName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Premuim")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnnonceId");

                    b.ToTable("Annonces");

                    b.HasData(
                        new
                        {
                            AnnonceId = 1,
                            AnnonceName = "trotinette",
                            Desc = "nice",
                            Premuim = false,
                            Price = 15.0,
                            UserId = 1
                        },
                        new
                        {
                            AnnonceId = 2,
                            AnnonceName = "sendala",
                            Desc = "nice",
                            Premuim = false,
                            Price = 30.0,
                            UserId = 2
                        },
                        new
                        {
                            AnnonceId = 3,
                            AnnonceName = "Audi A3",
                            Desc = "nice",
                            Premuim = true,
                            Price = 250000.0,
                            UserId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
