// <auto-generated />
using System;
using Annonce.Services.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annonce.Services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Annonce.Services.Models.Annonces", b =>
                {
                    b.Property<int>("AnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnonceId"), 1L, 1);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Premuim")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnonceId");

                    b.ToTable("Annonces");

                    b.HasData(
                        new
                        {
                            AnnonceId = 1,
                            Desc = "telephone economique",
                            Image = new byte[0],
                            Premuim = false,
                            Price = 233.0,
                            UserId = 1,
                            title = "nokia vintage"
                        },
                        new
                        {
                            AnnonceId = 2,
                            Desc = "pc gamer neuf spec nvidia rtx ram 32g stockage 1tb",
                            Image = new byte[0],
                            Premuim = false,
                            Price = 12000.0,
                            UserId = 1,
                            title = "pc gamer neuf"
                        },
                        new
                        {
                            AnnonceId = 3,
                            Desc = "trotinette electrique xiaomi 30h charge",
                            Image = new byte[0],
                            Premuim = false,
                            Price = 3500.0,
                            UserId = 1,
                            title = "trotinnete electrique xiaomi"
                        },
                        new
                        {
                            AnnonceId = 4,
                            Desc = "Golf8 importe de bern",
                            Image = new byte[0],
                            Premuim = true,
                            Price = 335000.0,
                            UserId = 1,
                            title = "Golf8 importe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
